toolbar:
  - styleselect | bold italic | undo redo | uploadimage | link | table | code | codesample | preview | visualblocks | charmap |forecolor backcolor | bullist numlist 
plugins:
  - uploadimage
  - link
  - table
  - code
  - preview
  - wordcount
  - visualblocks
  - charmap
  - textcolor
  - lists
  - advlist
